engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: tests/phpmdruleset.xml
ratings:
  paths:
  - "**.php"
exclude_paths:
- test/
