engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseMethodName:
        allow-underscore: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- test/
