language: php

# list any PHP version you want to test against
php:
  - 5.6
  - 7.0

# Commands to be run before your environment runs.
install: composer install --dev

# omitting "script:" will default to phpunit
script: phpunit --configuration test/phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - bin/test-reporter
addons:
    code_climate:
        repo_token: b6b3650b1202896874a998e58c04133d4ea8f24e073bbd594d5ab9e43a64b560
