<?php

namespace Gems\HL7\Test;

use Gems\HL7\Node\Message;
use Gems\HL7\Segment\EVNSegment;
use Gems\HL7\Segment\MRGSegment;
use Gems\HL7\Segment\MSASegment;
use Gems\HL7\Segment\MSHSegment;
use Gems\HL7\Segment\PIDSegment;
use Gems\HL7\Segment\PV1Segment;
use Gems\HL7\Segment\SCHSegment;
use Gems\HL7\Unserializer;
use PHPUnit_Framework_TestCase;
use Zalt\Loader\ProjectOverloader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-12 at 12:28:21.
 */
class TestAbstract extends PHPUnit_Framework_TestCase
{

    protected $map = [
        'EVN' => EVNSegment::class,
        'MRG' => MRGSegment::class,
        'MSA' => MSASegment::class,        
        'MSH' => MSHSegment::class,
        'PID' => PIDSegment::class,
        'PV1' => PV1Segment::class,
        'SCH' => SCHSegment::class,
    ];

    /**
     * @var Unserializer
     */
    protected $unserializer;

    protected function setUp()
    {
        $loader = new ProjectOverloader([
            'Gems',
            'PharmaIntelligence',
        ]);
        $loader->createServiceManager();
        
        $this->unserializer = $loader->create('HL7\\Unserializer');
    }

    /**
     *
     * @staticvar array $map
     * @param type $filename
     * @return Message
     */
    protected function _getMessageFromFile($filename)
    {
        $testHl7 = file_get_contents($filename);

        $message = $this->unserializer->loadMessageFromString($testHl7, $this->map);

        return $message;
    }

}
