<?php
namespace Gems\HL7\Message;

use PharmaIntelligence\HL7\Unserializer;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-09 at 13:22:05.
 */
class ACKTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ACK
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $file = 'resources/orm.txt';
        $testHl7 = file_get_contents($file);
        // file_put_contents($file, str_replace(chr(10), chr(13), $testHl7));
        // return;
        $unserializer = new Unserializer();
        $map = array(
            'MSH' => 'Gems\HL7\Segment\MSHSegment'
        );
        $message = $unserializer->loadMessageFromString($testHl7, $map);
        $this->object = new ACK($message);
    }
    
    public function testAck()
    {
        $expected = "MSH|^~\&|CTB||HISCOM|COMZIS|20130308020654||ACK^A08|123456|P|2.4|||AL|NE\rMSA|AA|123456";
        $this->assertEquals($this->object->__toString(), $expected);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
