<?php
namespace Gems\HL7\Message;

use PHPUnit_Framework_TestCase;
use Zalt\Loader\ProjectOverloader;
use const TEST_DIR;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-09 at 13:22:05.
 */
class ACKTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ACK
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $loader = new ProjectOverloader([
            'Gems\\Clover',
            'Gems',
            'PharmaIntelligence',
        ]);
        $loader->createServiceManager();

        $unserializer        = $loader->create('HL7\\Unserializer');
        
        $file = TEST_DIR . '/resources/orm.txt';
        $testHl7 = file_get_contents($file);
        // file_put_contents($file, str_replace(chr(10), chr(13), $testHl7));
        // return;
        
        $map = array(
            'MSH' => 'Gems\HL7\Segment\MSHSegment'
        );
        $message = $unserializer->loadMessageFromString($testHl7, $map);
        $this->object = new ACK($message);
    }
    
    public function testAck()
    {
        $expected = "MSH|^~\&|TESTSYSTEM|TESTFACILITY|NES|NINTENDO|20170103075313||ACK^A08|4208|T|2.4|||AL|NE|NLD|Windows-1252\rMSA|AA|4208";
        $this->assertEquals($this->object->__toString(), $expected);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
