<?php

namespace Gems\HL7\Segment;

use PHPUnit_Framework_TestCase;
use Zalt\Loader\ProjectOverloader;
use const TEST_DIR;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-12 at 15:09:17.
 */
class MSHSegmentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MSHSegment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $loader = new ProjectOverloader([
            'Gems\\Clover',
            'Gems',
            'PharmaIntelligence',
        ]);
        $loader->createServiceManager();

        $unserializer        = $loader->create('HL7\\Unserializer');
        $file         = TEST_DIR . '/resources/orm.txt';
        $testHl7      = file_get_contents($file);
        $map          = array(
            'MSH' => 'Gems\HL7\Segment\MSHSegment'
        );
        $message      = $unserializer->loadMessageFromString($testHl7, $map);
        $mshs         = $message->getSegmentsByName('MSH');
        $this->object = $mshs[0];
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::getSendingApplication
     * @todo   Implement testGetSendingApplication().
     * /
    public function testGetSendingApplication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::getSendingFacility
     * @todo   Implement testGetSendingFacility().
     * /
    public function testGetSendingFacility() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::getReceivingApplication
     * @todo   Implement testGetReceivingApplication().
     * /
    public function testGetReceivingApplication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::getReceivingFacility
     * @todo   Implement testGetReceivingFacility().
     * /
    public function testGetReceivingFacility() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::getDateTimeOfMessage
     * @todo   Implement testGetDateTimeOfMessage().
     */
    public function testGetDateTimeOfMessage() {
        $this->assertEquals('20170103075313', $this->object->getDateTimeOfMessage()->getDateTime());
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::getMessageType
     * @todo   Implement testGetMessageType().
     * /
    public function testGetMessageType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::getMessageControlId
     * @todo   Implement testGetMessageControlId().
     * /
    public function testGetMessageControlId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::getProcessingId
     * @todo   Implement testGetProcessingId().
     * /
    public function testGetProcessingId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::getVersionId
     * @todo   Implement testGetVersionId().
     * /
    public function testGetVersionId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::setSendingApplication
     * @todo   Implement testSetSendingApplication().
     * /
    public function testSetSendingApplication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::setSendingFacility
     * @todo   Implement testSetSendingFacility().
     * /
    public function testSetSendingFacility() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::setReceivingApplication
     * @todo   Implement testSetReceivingApplication().
     * /
    public function testSetReceivingApplication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::setReceivingFacility
     * @todo   Implement testSetReceivingFacility().
     * /
    public function testSetReceivingFacility() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::setDateTimeOfMessage
     * @todo   Implement testSetDateTimeOfMessage().
     * /
    public function testSetDateTimeOfMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::setMessageType
     * @todo   Implement testSetMessageType().
     * /
    public function testSetMessageType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::setMessageControlId
     * @todo   Implement testSetMessageControlId().
     * /
    public function testSetMessageControlId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::setProcessingId
     * @todo   Implement testSetProcessingId().
     * /
    public function testSetProcessingId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\MSHSegment::setVersionId
     * @todo   Implement testSetVersionId().
     * /
    public function testSetVersionId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    // */
}
