<?php

namespace Gems\HL7\Segment;

use DateTime;
use Gems\HL7\Type\TS;
use PharmaIntelligence\HL7\Unserializer;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-12 at 09:06:41.
 */
class PIDSegmentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PIDSegment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $file         = 'resources/orm.txt';
        $testHl7      = file_get_contents($file);
        $unserializer = new Unserializer();
        $map          = array(
            'PID' => 'Gems\HL7\Segment\PIDSegment'
        );
        $message      = $unserializer->loadMessageFromString($testHl7, $map);
        $pids         = $message->getSegmentsByName('PID');
        $this->object = $pids[0];
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Gems\HL7\Segment\PIDSegment::getSetId
     */
    public function testGetSetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gems\HL7\Segment\PIDSegment::getPatientId
     */
    public function testGetPatientIdValue() {
        // Only left for backward compatibility, should be null
        $this->assertEquals(null, $this->object->getPatientId()->getId());
    }

    /**
     * @covers Gems\HL7\Segment\PIDSegment::getPatientIdentifierList
     */
    public function testGetPatientIdentifierListType() {
        $this->assertInternalType('array', $this->object->getPatientIdentifierList());
    }

    /**
     * @covers Gems\HL7\Segment\PIDSegment::getPatientIdentifierList
     */
    public function testGetPatientIdentifierListContent() {
        $records = $this->object->getPatientIdentifierList();
        $this->assertInstanceOf('Gems\HL7\Type\CX', $records[0]);
    }

    /**
     * @covers Gems\HL7\Segment\PIDSegment::getPatientIdentifierList
     */
    public function testGetPatientIdentifierListPIValue() {
        $id = $this->object->getPatientIdentifierByIdentifier('PI')->getId();

        $this->assertEquals('8101892', $id);
    }

    public function testGetPhoneHomeNumber()
    {
        $homeNr = $this->object->getPhoneHome();
        $this->assertEquals('06-43064759', $homeNr[0]->getPhoneNumber());
    }

    public function testGetBirthDateTime()
    {
        $this->assertEquals('19820703', $this->object->getBirthDateTime()->getDate());
    }

    public function testGetDeathDateTime()
    {
        $this->assertEquals(null, $this->object->getDeathDateTime()->getDate());
    }

}
