<?php

namespace Gems\HL7\Segment;

use PharmaIntelligence\HL7\Unserializer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-25 at 08:38:48.
 */
class PV1SegmentTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PV1Segment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $file         = 'resources/orm.txt';
        $testHl7      = file_get_contents($file);
        $unserializer = new Unserializer();
        $map          = array(
            'PV1' => 'Gems\HL7\Segment\PV1Segment'
        );
        $message      = $unserializer->loadMessageFromString($testHl7, $map);
        $pv1s         = $message->getSegmentsByName('PV1');
        $this->object = $pv1s[0];
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Gems\HL7\Segment\PV1Segment::getSetId
     */
    public function testGetSetId() {
        $this->assertEquals(1, $this->object->getSetId());
    }

    /**
     * @covers Gems\HL7\Segment\PV1Segment::getPatientClass
     */
    public function testGetPatientClass() {
        $this->assertEquals('I', $this->object->getPatientClass());
    }

    /**
     * @covers Gems\HL7\Segment\PV1Segment::getPatientLocation()
     */
    public function testGetPatientLocation() {
        $location = $this->object->getPatientLocation();
        $expected = "4ZOB^SK4166^01";
        $this->assertEquals($expected, (string) $this->object->getPatientLocation());
    }
    
    /**
     * @covers Gems\HL7\Segment\PV1Segment::getAdmissionType()
     */
    public function testGetAdmissionType() {
        $this->assertEquals('R', $this->object->getAdmissionType());
    }

}
